---
extends: "stylelint-config-standard"
plugins:
  - "stylelint-scss"
rules:
  color-named: never
#  declaration-block-properties-order:
#    - alphabetical
#    - severity: warning
  declaration-colon-newline-after: null
  declaration-empty-line-before: null
  rule-empty-line-before: never
  at-rule-empty-line-before: never
#  declaration-property-value-blacklist:
#    "/^border/":
#      - none
  function-url-quotes: always
  indentation:
    - 2
    - ignore:
      - value
  max-empty-lines:
    ignore:
      - comments
  max-nesting-depth: 4
  no-duplicate-selectors: true
  no-missing-end-of-source-newline: true
  number-max-precision: 4
  property-no-vendor-prefix: true
  selector-class-pattern: "^((?:-{1,2}|_{2})?[a-z0-9]+(?:(?:-{1,2}|_{2})[a-z0-9]+)*)(?:-{1,2}|_{2})?$"
  selector-max-compound-selectors: null #4
  selector-max-specificity:
    - "1,5,0" #"0,3,0"
  selector-no-qualifying-type:
    - true
    - ignore:
      - class
      - type
  selector-pseudo-element-colon-notation: single
  string-quotes: single
  unit-blacklist:
    - - px
      - em
    - ignoreProperties:
      px:
        - "max-width"
  scss/at-import-no-partial-leading-underscore: true
  scss/at-import-partial-extension-blacklist:
    - scss
  scss/dollar-variable-colon-space-after: always
  scss/dollar-variable-colon-space-before: never
  scss/dollar-variable-no-missing-interpolation: true
#  scss/double-slash-comment-whitespace-inside: always
  scss/operator-no-unspaced: true
  scss/selector-no-redundant-nesting-selector: true
  media-feature-name-no-unknown:
    ignoreMediaFeatureNames:
      - "/regex/"
      - "string"
  function-linear-gradient-no-nonstandard-direction: false
  at-rule-no-unknown:
    ignoreAtRules:
      - "/regex/"
      - "for"